### ISSUE TITLE
no such file or directory ap-angular2-fullcalendar.js

### ISSUE THREAD

**Issue by emmanuel128** [lbertenasco/ap-ng2-fullcalendar#74] opened 2018-02-07 13:47 UTC
HI, I followed your installation steps but I kept getting this error.
``` powershell
[09:31:05] 'build.bundles.app' errored after 1.26 s
[09:31:05] Error on fetch for ap-angular2-fullcalendar.js at file:///C:/XXXX/XXXXXX/node_modules/ap-angular2-fullcalendar.js
        Loading dist/tmp/app/itinerary/itinerary.module.js
        Loading dist/tmp/app/app.module.js
        Loading dist/tmp/app/main.js
        Error: ENOENT: no such file or directory, open 'C:\XXXX\XXXXXX\node_modules\ap-angular2-fullcalendar.js'
    at Error (native)
[09:31:05] 'build.prod' errored after 25 s
[09:31:05] Error in plugin 'run-sequence(build.bundles.app)'
Message:
    Error on fetch for ap-angular2-fullcalendar.js at file:///C:/XXXX/XXXXXX/node_modules/ap-angular2-fullcalendar.js
        Loading dist/tmp/app/itinerary/itinerary.module.js
        Loading dist/tmp/app/app.module.js
        Loading dist/tmp/app/main.js
        ENOENT: no such file or directory, open 'C:\XXXX\XXXXXX\node_modules\ap-angular2-fullcalendar.js'
Details:
    originalErr: Error: ENOENT: no such file or directory, open 'C:\XXXX\XXXXXX\node_modules\ap-angular2-fullcalendar.js'
Stack:
Error on fetch for ap-angular2-fullcalendar.js at file:///C:/XXXX/XXXXXX/node_modules/ap-angular2-fullcalendar.js
        Loading dist/tmp/app/itinerary/itinerary.module.js
        Loading dist/tmp/app/app.module.js
        Loading dist/tmp/app/main.js
        Error: ENOENT: no such file or directory, open 'C:\XXXX\XXXXXX\node_modules\ap-angular2-fullcalendar.js'
    at Error (native)
```

**Versions:** 

`npm -v 3.10.10`
`node -v 6.11.0`
`"@angular/compiler-cli": "~2.2.0"`
`"@types/jquery": "^2.0.45"`
`"jquery": "^3.1.0"`

**Comment by emmanuel128** [comment] 2018-02-07 14:22
I created a new project and this error came out
![image](https://user-images.githubusercontent.com/14911235/35921317-b2350136-0bf0-11e8-8fe4-80ad13d3ac1a.png)

**Comment by lbertenasco** [comment] 2018-02-07 14:49
Hi @emmanuel128 
What version of angular are you using?
`ng -v`
And what version of `ap-ng2-fullcalendar` are you using?
`cat package.json | grep fullcalendar`

**Comment by emmanuel128** [comment] 2018-02-07 17:06
ng -v
```
Angular CLI: 1.6.7
Node: 6.11.0
OS: win32 x64
Angular: 2.2.4
... common, compiler, compiler-cli, core, forms, http
... platform-browser, platform-browser-dynamic, platform-server

@angular/cli: 1.6.7
@angular/router: 3.2.4
@angular/tsc-wrapped: 0.3.0
@angular/upgrade: 2.2.0
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.29
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.7
@schematics/angular: 0.1.17
typescript: 2.3.2
webpack: 3.10.0
```

package.json
``` json
{
  "name": "****",
  "version": "0.0.0",
  "description": "",
  "scripts": {
    "build.dev": "gulp build.dev --color --config-env dev",
    "build.dev.watch": "gulp build.dev.watch --color --base Resources/",
    "build.e2e": "gulp build.e2e --color",
    "build.prod": "gulp build.prod --color --config-env prod --base Resources/",
    "build.prod.watch": "gulp build.prod.watch --color --config-env prod --base Resources/",
    "build.test": "gulp build.test --color",
    "build.test.watch": "gulp build.test.watch --color",
    "build.tools": "gulp build.tools",
    "generate.manifest": "gulp generate.manifest --color",
    "e2e": "protractor",
    "e2e.live": "protractor --elementExplorer",
    "gulp": "gulp",
    "karma": "karma",
    "karma.start": "karma start",
    "postinstall": "gulp check.versions && npm prune && gulp webdriver",
    "reinstall": "npm cache clean && npm install",
    "serve.coverage": "remap-istanbul -b src/ -i coverage/coverage-final.json -o coverage -t html && npm run gulp -- serve.coverage --color",
    "serve.dev": "gulp serve.dev --color --config-env dev",
    "serve.e2e": "gulp serve.e2e --color",
    "serve.prod": "gulp serve.prod --color --config-env prod",
    "start": "gulp serve.dev --color --config-env dev",
    "tasks.list": "gulp --tasks-simple --color",
    "test": "gulp test --color",
    "e2e.ci": "gulp build.prod --color && gulp build.js.e2e --color && gulp e2e --color",
    "tests.all": "npm test && npm run e2e.ci",
    "webdriver-start": "webdriver-manager start",
    "webdriver-update": "webdriver-manager update",
    "watch": "gulp build.prod.watch --color",
    "copy-dev": "gulp build.dev.copy --color"
  },
  "author": "",
  "license": "MIT",
  "devDependencies": {
    "@angular/compiler-cli": "~2.2.0",
    "@angular/platform-server": "~2.2.0",
    "@angular/tsc-wrapped": "0.3.0",
    "@types/async": "^2.0.32",
    "@types/browser-sync": "^0.0.34",
    "@types/core-js": "^0.9.34",
    "@types/express": "^4.0.33",
    "@types/gulp": "4.0.3",
    "@types/gulp-filter": "^3.0.29",
    "@types/gulp-load-plugins": "^0.0.28",
    "@types/gulp-protractor": "^1.0.29",
    "@types/gulp-sass": "^0.0.29",
    "@types/gulp-util": "^3.0.29",
    "@types/jasmine": "^2.5.35",
    "@types/jquery": "^2.0.34",
    "@types/lodash": "^4.14.64",
    "@types/node": "^6.0.45",
    "@types/protractor": "^1.5.20",
    "@types/rimraf": "0.0.28",
    "@types/run-sequence": "^0.0.28",
    "@types/selenium-webdriver": "2.44.*",
    "@types/systemjs": "^0.19.31",
    "@types/yargs": "^0.0.34",
    "@types/zone.js": "^0.0.27",
    "async": "^2.1.1",
    "autoprefixer": "^6.5.1",
    "browser-sync": "^2.17.3",
    "codelyzer": "~1.0.0-beta.3",
    "colorguard": "^1.2.0",
    "compodoc": "0.0.8",
    "compression": "^1.6.2",
    "connect": "^3.4.1",
    "connect-history-api-fallback": "^1.3.0",
    "connect-livereload": "^0.6.0",
    "cssnano": "^3.7.7",
    "deep-extend": "^0.4.1",
    "doiuse": "^2.4.1",
    "event-stream": "^3.3.4",
    "express": "~4.14.0",
    "express-history-api-fallback": "^2.0.0",
    "extend": "^3.0.0",
    "gulp": "^3.9.1",
    "gulp-cached": "^1.1.0",
    "gulp-clean-css": "^2.0.11",
    "gulp-concat": "^2.6.0",
    "gulp-concat-css": "^2.3.0",
    "gulp-filter": "^4.0.0",
    "gulp-inject": "^4.1.0",
    "gulp-inline-ng2-template": "^4.0.0",
    "gulp-load-plugins": "^1.3.0",
    "gulp-plumber": "~1.1.0",
    "gulp-postcss": "^6.2.0",
    "gulp-progeny": "^0.3.1",
    "gulp-protractor": "^3.0.0",
    "gulp-replace": "^0.5.4",
    "gulp-sass": "^2.3.2",
    "gulp-sass-lint": "^1.2.0",
    "gulp-shell": "~0.5.2",
    "gulp-sourcemaps": "2.2.0",
    "gulp-template": "^4.0.0",
    "gulp-tslint": "^6.1.2",
    "gulp-typescript": "^3.1.7",
    "gulp-uglify": "^2.0.0",
    "gulp-util": "^3.0.7",
    "gulp-watch": "^4.3.10",
    "is-ci": "^1.0.9",
    "isstream": "^0.1.2",
    "jasmine-core": "~2.5.2",
    "jasmine-spec-reporter": "^2.7.0",
    "karma": "~1.3.0",
    "karma-chrome-launcher": "~2.0.0",
    "karma-coverage": "^1.1.1",
    "karma-jasmine": "~1.0.2",
    "karma-mocha-reporter": "^2.2.0",
    "karma-remap-istanbul": "^0.2.1",
    "lodash": "^4.17.4",
    "merge-stream": "^1.0.0",
    "open": "0.0.5",
    "postcss-reporter": "^2.0.0",
    "protractor": "^4.0.9",
    "remap-istanbul": "^0.7.0",
    "rimraf": "^2.5.4",
    "run-sequence": "^1.2.2",
    "semver": "^5.3.0",
    "serve-static": "^1.11.1",
    "slash": "~1.0.0",
    "stream-series": "^0.1.1",
    "stylelint": "^7.0.2",
    "stylelint-config-standard": "^14.0.0",
    "supports-color": "^3.1.2",
    "systemjs-builder": "0.15.14",
    "tildify": "^1.2.0",
    "tiny-lr": "^1.0.3",
    "traceur": "^0.0.111",
    "ts-node": "^3.1.0",
    "tslint": "^3.15.1",
    "tslint-stylish": "2.1.0-beta",
    "typescript": "2.4.0",
    "typings": "^2.0.0",
    "vinyl-buffer": "^1.0.0",
    "vinyl-source-stream": "^1.1.0",
    "walk": "^2.3.9",
    "yargs": "^6.0.0"
  },
  "dependencies": {
    "@angular/common": "~2.2.0",
    "@angular/compiler": "~2.2.0",
    "@angular/core": "~2.2.0",
    "@angular/forms": "~2.2.0",
    "@angular/http": "~2.2.0",
    "@angular/platform-browser": "~2.2.0",
    "@angular/platform-browser-dynamic": "~2.2.0",
    "@angular/router": "~3.2.0",
    "@angular/upgrade": "2.2.0",
    "@ng-idle/core": "^2.0.0-beta.12",
    "@types/jquery": "^2.0.45",
    "@types/underscore": "^1.7.36",
    "angular-sweetalert-service": "^2.0.2",
    "angular2-cookie": "^1.2.6",
    "angular2-csv": "^0.2.1",
    "angular2-datepicker": "^1.0.4",
    "angular2-froala-wysiwyg": "^2.6.0",
    "angular2-http-file-upload": "^1.0.6",
    "angular2-infinite-scroll": "^0.3.1",
    "angular2-jwt": "^0.1.25",
    "angular2-ladda": "^1.2.1",
    "angular2-modal": "^2.0.2",
    "angular2-moment": "^1.1.0",
    "angular2-select": "^1.0.0-beta.3",
    "angular2-text-mask": "^8.0.1",
    "angular2-truncate": "^0.1.3",
    "angular2-ui-switch": "^1.2.0",
    "bootstrap": "^3.3.7",
    "chart.js": "^2.6.0",
    "core-js": "^2.4.1",
    "es6-module-loader": "^0.17.11",
    "font-awesome": "^4.7.0",
    "gulp-jade": "^1.1.0",
    "intl": "^1.2.5",
    "jquery": "^3.1.0",
    "jw-bootstrap-switch-ng2": "^1.0.10",
    "ladda": "^1.0.0",
    "localStorage": "^1.0.3",
    "metismenu": "^2.7.0",
    "minimatch": "^3.0.3",
    "moment": "^2.18.1",
    "mydatepicker": "^1.10.2",
    "ng-idle": "^1.3.2",
    "ng-select": "^1.0.0-beta.6",
    "ng-spin-kit": "^2.0.0",
    "ng2-charts": "^1.6.0",
    "ng2-datepicker": "^1.8.3",
    "ng2-datetime": "^1.4.0",
    "ng2-dnd": "^2.2.2",
    "ng2-signalr": "^2.1.0",
    "ng2-spin-kit": "^1.3.0",
    "ng2-toasty": "^2.3.0",
    "ng2-translate": "^5.0.0",
    "ngx-pipes": "^1.6.3",
    "reflect-metadata": "^0.1.9",
    "rxjs": "5.1.1",
    "signalr": "^2.2.2",
    "systemjs": "0.19.27",
    "tinymce": "^4.6.3",
    "underscore": "^1.8.3",
    "zone.js": "0.7.7"
  }
}
```

**Comment by lbertenasco** [comment] 2018-02-07 17:22
The issue is that you are using angular version 2.2,
And should be using angular 5.
Sadly this package does not support older versions of angular.
Upgrade your angular and try again :)

I'm closing this issue since it's related to an older version of angular.
Feel free to re-open it.

**Closed as completed by lbertenasco** 2018-02-07 17:22 UTC

**Comment by emmanuel128** [comment] 2018-02-07 17:26
Thanks!

do you know if there's a way to use full calendar on angular 2.X?

**Comment by lbertenasco** [comment] 2018-02-07 20:14
Try with `ap-angular2-fullcalendar` version `1.0.19`
`npm install ap-angular2-fullcalendar@1.0.19 --save`
Beware it's a really old version and might have a few unsolved bugs.

**Comment by emmanuel128** [comment] 2018-02-07 21:25
![image](https://user-images.githubusercontent.com/14911235/35942379-d18e8210-0c2b-11e8-96c7-f8df591371af.png)

**Comment by emmanuel128** [comment] 2018-02-07 21:43
I'm still getting the same error
``` powershell
[17:41:11] Error on fetch for ap-angular2-fullcalendar.js at file:///C:/XXXX/XXXXXX/node_modules/ap-angular2-fullcalendar.js
        Loading dist/tmp/app/itinerary/itinerary.module.js
        Loading dist/tmp/app/app.module.js
        Loading dist/tmp/app/main.js
        Error: ENOENT: no such file or directory, open 'C:\XXXX\XXXXXX\node_modules\ap-angular2-fullcalendar.js'
    at Error (native)
```

**Comment by lbertenasco** [comment] 2018-02-08 15:03
`file:///C:/XXXX/XXXXXX/node_modules/ap-angular2-fullcalendar.js`
This route will never work.
This should be the correct route, maybe it's an issue with windows and your ng-cli version...
`file:///C:/XXXX/XXXXXX/node_modules/ap-angular2-fullcalendar/ap-angular2-fullcalendar.js`
I'm sorry I cannot help you more.

**Comment by emmanuel128** [comment] 2018-02-12 13:30
i found out that this project is using System.js, not webpack... does this affect something?

**Comment by lbertenasco** [comment] 2018-02-13 13:23
Yes, you should find a way to import the library using system.js.
